version: '3.8'

services:
  product:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=1433
      - DB_NAME=DegaTEXTILE
      - DB_USER=sa
      - DB_PASSWORD=%%Dg2936%%
      - JWT_SECRET=tuRhMSDerrNv6RQbKTt7C2vlE5Yl29
    networks:
      - product-app
    volumes:
      - .:/app

networks:
  product-app:
    driver: bridge
