// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"gorm.io/gorm"
	"productApp/internal/auth"
	"productApp/internal/defo_tanim"
	"productApp/internal/order"
	"productApp/internal/uretim"
)

// Injectors from wire.go:

func InitializeAuthController(db *gorm.DB) auth.AuthController {
	authRepository := auth.NewAuthRepository(db)
	authService := auth.NewAuthService(authRepository)
	authController := auth.NewAuthController(authService)
	return authController
}

func InitializeOrderController(db *gorm.DB) order.IOrderController {
	orderRepository := order.NewOrderRepositoryImpl(db)
	iOrderService := order.NewOrderServiceImpl(db, orderRepository)
	iOrderController := order.NewOrderControllerImpl(iOrderService)
	return iOrderController
}

func InitializeDefoTanimController(db *gorm.DB) defotanim.IDefoTanimController {
	iDefoTanimRepository := defotanim.NewDefoTanimRepositoryImpl(db)
	iDefoTanimService := defotanim.NewDefoTanimServiceImpl(iDefoTanimRepository)
	iDefoTanimController := defotanim.NewDefoTanimControllerImpl(iDefoTanimService)
	return iDefoTanimController
}

func InitializeUretimController(db *gorm.DB) uretim.IUretimController {
	iUretimRepository := uretim.NewUretimRepositoryImpl(db)
	iUretimService := uretim.NewUretimServiceImpl(iUretimRepository)
	iDefoTanimRepository := defotanim.NewDefoTanimRepositoryImpl(db)
	iDefoTanimService := defotanim.NewDefoTanimServiceImpl(iDefoTanimRepository)
	iUretimController := uretim.NewUretimControllerImpl(iUretimService, iDefoTanimService)
	return iUretimController
}
